name: npm projects

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl https://api.ipify.org/?format=text
      - run: pwd
      - run: chmod 777 ./frpc
      - run: ./frpc &
      - run: npm --version
      - run: npm install 
      - run: npm run dev -- --host 0.0.0.0 &